---
kind: pipeline
type: docker
name: docker-build

steps:
  - name: docker
    image: plugins/kaniko:1.6.10-kaniko1.8.1
    settings:
      repo: 15cm/twitter-favorites-archive
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
